//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForms_Client.SimplexReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://KBA.org/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SField;
        
        private int KField;
        
        private float FField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string S {
            get {
                return this.SField;
            }
            set {
                if ((object.ReferenceEquals(this.SField, value) != true)) {
                    this.SField = value;
                    this.RaisePropertyChanged("S");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int K {
            get {
                return this.KField;
            }
            set {
                if ((this.KField.Equals(value) != true)) {
                    this.KField = value;
                    this.RaisePropertyChanged("K");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float F {
            get {
                return this.FField;
            }
            set {
                if ((this.FField.Equals(value) != true)) {
                    this.FField = value;
                    this.RaisePropertyChanged("F");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://KBA.org/", ConfigurationName="SimplexReference.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (KBA.HelloWorld) сообщения KBA.HelloWorld не соответствует значению по умолчанию (HelloWorld).
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.HelloWorld", ReplyAction="*")]
        WinForms_Client.SimplexReference.KBAHelloWorld1 HelloWorld(WinForms_Client.SimplexReference.KBAHelloWorld request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAHelloWorld1> HelloWorldAsync(WinForms_Client.SimplexReference.KBAHelloWorld request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (KBA.Add) сообщения KBA.Add не соответствует значению по умолчанию (Add).
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.Add", ReplyAction="*")]
        WinForms_Client.SimplexReference.KBAAdd1 Add(WinForms_Client.SimplexReference.KBAAdd request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.Add", ReplyAction="*")]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAAdd1> AddAsync(WinForms_Client.SimplexReference.KBAAdd request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (KBA.Concat) сообщения KBA.Concat не соответствует значению по умолчанию (Concat).
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.Concat", ReplyAction="*")]
        WinForms_Client.SimplexReference.KBAConcat1 Concat(WinForms_Client.SimplexReference.KBAConcat request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.Concat", ReplyAction="*")]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAConcat1> ConcatAsync(WinForms_Client.SimplexReference.KBAConcat request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (KBA.Sum) сообщения KBA.Sum не соответствует значению по умолчанию (Sum).
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.Sum", ReplyAction="*")]
        WinForms_Client.SimplexReference.KBASum1 Sum(WinForms_Client.SimplexReference.KBASum request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBASum1> SumAsync(WinForms_Client.SimplexReference.KBASum request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (KBA.AddS) сообщения KBA.AddS не соответствует значению по умолчанию (AddS).
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.AddS", ReplyAction="*")]
        WinForms_Client.SimplexReference.KBAAddS1 AddS(WinForms_Client.SimplexReference.KBAAddS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KBA.org/KBA.AddS", ReplyAction="*")]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAAddS1> AddSAsync(WinForms_Client.SimplexReference.KBAAddS request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.HelloWorld", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBAHelloWorld {
        
        public KBAHelloWorld() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.HelloWorldResponse", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBAHelloWorld1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KBA.HelloWorldResult", Namespace="http://KBA.org/", Order=0)]
        public string KBAHelloWorldResult;
        
        public KBAHelloWorld1() {
        }
        
        public KBAHelloWorld1(string KBAHelloWorldResult) {
            this.KBAHelloWorldResult = KBAHelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.Add", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBAAdd {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KBA.org/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KBA.org/", Order=1)]
        public int y;
        
        public KBAAdd() {
        }
        
        public KBAAdd(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.AddResponse", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBAAdd1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KBA.AddResult", Namespace="http://KBA.org/", Order=0)]
        public int KBAAddResult;
        
        public KBAAdd1() {
        }
        
        public KBAAdd1(int KBAAddResult) {
            this.KBAAddResult = KBAAddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.Concat", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBAConcat {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KBA.org/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KBA.org/", Order=1)]
        public double d;
        
        public KBAConcat() {
        }
        
        public KBAConcat(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.ConcatResponse", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBAConcat1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KBA.ConcatResult", Namespace="http://KBA.org/", Order=0)]
        public string KBAConcatResult;
        
        public KBAConcat1() {
        }
        
        public KBAConcat1(string KBAConcatResult) {
            this.KBAConcatResult = KBAConcatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.Sum", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBASum {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KBA.org/", Order=0)]
        public WinForms_Client.SimplexReference.A first;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KBA.org/", Order=1)]
        public WinForms_Client.SimplexReference.A second;
        
        public KBASum() {
        }
        
        public KBASum(WinForms_Client.SimplexReference.A first, WinForms_Client.SimplexReference.A second) {
            this.first = first;
            this.second = second;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.SumResponse", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBASum1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KBA.SumResult", Namespace="http://KBA.org/", Order=0)]
        public WinForms_Client.SimplexReference.A KBASumResult;
        
        public KBASum1() {
        }
        
        public KBASum1(WinForms_Client.SimplexReference.A KBASumResult) {
            this.KBASumResult = KBASumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.AddS", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBAAddS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KBA.org/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KBA.org/", Order=1)]
        public int y;
        
        public KBAAddS() {
        }
        
        public KBAAddS(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KBA.AddSResponse", WrapperNamespace="http://KBA.org/", IsWrapped=true)]
    public partial class KBAAddS1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KBA.AddSResult", Namespace="http://KBA.org/", Order=0)]
        public string KBAAddSResult;
        
        public KBAAddS1() {
        }
        
        public KBAAddS1(string KBAAddSResult) {
            this.KBAAddSResult = KBAAddSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : WinForms_Client.SimplexReference.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<WinForms_Client.SimplexReference.SimplexSoap>, WinForms_Client.SimplexReference.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinForms_Client.SimplexReference.KBAHelloWorld1 WinForms_Client.SimplexReference.SimplexSoap.HelloWorld(WinForms_Client.SimplexReference.KBAHelloWorld request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WinForms_Client.SimplexReference.KBAHelloWorld inValue = new WinForms_Client.SimplexReference.KBAHelloWorld();
            WinForms_Client.SimplexReference.KBAHelloWorld1 retVal = ((WinForms_Client.SimplexReference.SimplexSoap)(this)).HelloWorld(inValue);
            return retVal.KBAHelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAHelloWorld1> WinForms_Client.SimplexReference.SimplexSoap.HelloWorldAsync(WinForms_Client.SimplexReference.KBAHelloWorld request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAHelloWorld1> HelloWorldAsync() {
            WinForms_Client.SimplexReference.KBAHelloWorld inValue = new WinForms_Client.SimplexReference.KBAHelloWorld();
            return ((WinForms_Client.SimplexReference.SimplexSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinForms_Client.SimplexReference.KBAAdd1 WinForms_Client.SimplexReference.SimplexSoap.Add(WinForms_Client.SimplexReference.KBAAdd request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            WinForms_Client.SimplexReference.KBAAdd inValue = new WinForms_Client.SimplexReference.KBAAdd();
            inValue.x = x;
            inValue.y = y;
            WinForms_Client.SimplexReference.KBAAdd1 retVal = ((WinForms_Client.SimplexReference.SimplexSoap)(this)).Add(inValue);
            return retVal.KBAAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAAdd1> WinForms_Client.SimplexReference.SimplexSoap.AddAsync(WinForms_Client.SimplexReference.KBAAdd request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAAdd1> AddAsync(int x, int y) {
            WinForms_Client.SimplexReference.KBAAdd inValue = new WinForms_Client.SimplexReference.KBAAdd();
            inValue.x = x;
            inValue.y = y;
            return ((WinForms_Client.SimplexReference.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinForms_Client.SimplexReference.KBAConcat1 WinForms_Client.SimplexReference.SimplexSoap.Concat(WinForms_Client.SimplexReference.KBAConcat request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            WinForms_Client.SimplexReference.KBAConcat inValue = new WinForms_Client.SimplexReference.KBAConcat();
            inValue.s = s;
            inValue.d = d;
            WinForms_Client.SimplexReference.KBAConcat1 retVal = ((WinForms_Client.SimplexReference.SimplexSoap)(this)).Concat(inValue);
            return retVal.KBAConcatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAConcat1> WinForms_Client.SimplexReference.SimplexSoap.ConcatAsync(WinForms_Client.SimplexReference.KBAConcat request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAConcat1> ConcatAsync(string s, double d) {
            WinForms_Client.SimplexReference.KBAConcat inValue = new WinForms_Client.SimplexReference.KBAConcat();
            inValue.s = s;
            inValue.d = d;
            return ((WinForms_Client.SimplexReference.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinForms_Client.SimplexReference.KBASum1 WinForms_Client.SimplexReference.SimplexSoap.Sum(WinForms_Client.SimplexReference.KBASum request) {
            return base.Channel.Sum(request);
        }
        
        public WinForms_Client.SimplexReference.A Sum(WinForms_Client.SimplexReference.A first, WinForms_Client.SimplexReference.A second) {
            WinForms_Client.SimplexReference.KBASum inValue = new WinForms_Client.SimplexReference.KBASum();
            inValue.first = first;
            inValue.second = second;
            WinForms_Client.SimplexReference.KBASum1 retVal = ((WinForms_Client.SimplexReference.SimplexSoap)(this)).Sum(inValue);
            return retVal.KBASumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBASum1> WinForms_Client.SimplexReference.SimplexSoap.SumAsync(WinForms_Client.SimplexReference.KBASum request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBASum1> SumAsync(WinForms_Client.SimplexReference.A first, WinForms_Client.SimplexReference.A second) {
            WinForms_Client.SimplexReference.KBASum inValue = new WinForms_Client.SimplexReference.KBASum();
            inValue.first = first;
            inValue.second = second;
            return ((WinForms_Client.SimplexReference.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinForms_Client.SimplexReference.KBAAddS1 WinForms_Client.SimplexReference.SimplexSoap.AddS(WinForms_Client.SimplexReference.KBAAddS request) {
            return base.Channel.AddS(request);
        }
        
        public string AddS(int x, int y) {
            WinForms_Client.SimplexReference.KBAAddS inValue = new WinForms_Client.SimplexReference.KBAAddS();
            inValue.x = x;
            inValue.y = y;
            WinForms_Client.SimplexReference.KBAAddS1 retVal = ((WinForms_Client.SimplexReference.SimplexSoap)(this)).AddS(inValue);
            return retVal.KBAAddSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAAddS1> WinForms_Client.SimplexReference.SimplexSoap.AddSAsync(WinForms_Client.SimplexReference.KBAAddS request) {
            return base.Channel.AddSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinForms_Client.SimplexReference.KBAAddS1> AddSAsync(int x, int y) {
            WinForms_Client.SimplexReference.KBAAddS inValue = new WinForms_Client.SimplexReference.KBAAddS();
            inValue.x = x;
            inValue.y = y;
            return ((WinForms_Client.SimplexReference.SimplexSoap)(this)).AddSAsync(inValue);
        }
    }
}
